# Generated by Django 4.2.23 on 2025-08-01 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='companycontactrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_records', to='crm_system.company'),
        ),
        migrations.AddField(
            model_name='companycontactrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='company',
            name='canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='crm_system.canton', verbose_name='Canton'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='crm_system.legalform', verbose_name='Legal form'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='crm_system.legalseat', verbose_name='Legal seat'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_system.companytype', verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='canton',
            index=models.Index(fields=['name'], name='crm_system__name_443e07_idx'),
        ),
        migrations.AddConstraint(
            model_name='canton',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name_canton', violation_error_message='Record with this name already exists'),
        ),
        migrations.AddIndex(
            model_name='companynote',
            index=models.Index(fields=['created_at'], name='crm_system__created_9b150e_idx'),
        ),
        migrations.AddIndex(
            model_name='companycontactrecord',
            index=models.Index(fields=['contacted_at'], name='crm_system__contact_d44bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['title'], name='crm_system__title_55eef5_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-created_at'], name='crm_system__created_0624a3_idx'),
        ),
    ]
